### PR TITLE
Fix MacOS tests

### PR DESCRIPTION
**Pull request by aaronmondal**
These didn't work due to issues with bash/echo on MacOS.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/449)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/449#-:-Nl0satO0TYWsq32Olqf:b-9jil5w)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @adam-singer and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/449#-:-Nl0ve9g3XvSUt3Hs8jX:b-3thtw4)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Review by adam-singer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/449#-:-Nl4hMW26-EN032mkMkU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by MarcusSorealheis** [comment]
Did someone run this on Mac OS? Looks good based on docs.

**Comment by MarcusSorealheis** [comment]
One thing that makes Mac's a bit trickier is the default shell is zsh, though most people move to Bash in this world.

**Comment by adam-singer** [comment]
@MarcusSorealheis confirmed I ran this on Mac with both bazel and cargo, I have also changed my default shell to bash. Confirmed that default shell being bash or zsh these tests now pass, thanks @aaronmondal !

**Pull request merged**
