### PR TITLE
Add Blake3 digest support

### PR DESCRIPTION
**Pull request by allada**
Fully support Blake3 digest upload format. This can increase
performance significantly for cases where hashing files is a
bottleneck.

closes #395

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/403)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@aaronmondal , @blakehatch 

Let me know and I'll show you how to review just the last commit (the other commits are already up in review).

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-:-NjQi8-OBAGX8qxRE37o:b-byfw0l)* status: 0 of 40 files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, 4 of 4 files at r2, 34 of 34 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/403)* status: all files reviewed, 5 unresolved discussions (waiting on @allada)

___
*[`cas/cas_main.rs` line 646 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQr2zxAmJBYxIIH8kn:-NjQr2zyBy5oH22ArcCs:b-uw12by) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/cas_main.rs#L646)):*
> ```XML
>             global_cfg
>                 .default_digest_hash_function
>                 .unwrap_or(ConfigDigestHashFunction::sha256),
> ```

I wonder whether we'd want to make blake3 the default here. I'm aware that bazel defaults to SHA2 (and blake3 support was only just added in 6.4), but this would force users to explicitly set `sha2` in their config. Considering that blake3 is ~15x faster than SHA2 this seems reasonable to me to make users think twice whether they actually want to keep using the significantly slower SHA2.
___
*[`cas/scheduler/tests/utils/scheduler_utils.rs` line 42 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsB-i8LISEwb634c0:-NjQsB-i8LISEwb634c1:b-xjfa1s) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/scheduler/tests/utils/scheduler_utils.rs#L42)):*
> ```XML
>         },
>         skip_cache_lookup: false,
>         digest_function: DigestHasherFunc::Sha256,
> ```

Is this intentionally hardcoded?
___
*[`cas/worker/tests/local_worker_test.rs` line 216 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsbsr4BIIhjLJ5OuY:-NjQsbsr4BIIhjLJ5OuZ:b2eiqqn) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/worker/tests/local_worker_test.rs#L216)):*
> ```XML
>             platform_properties: PlatformProperties::default(),
>             priority: 0,
>             load_timestamp: SystemTime::UNIX_EPOCH,
> ```

Will this still work on Windows?
___
*[`cas/worker/tests/local_worker_test.rs` line 305 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsnTsCg71HxVsL3jL:-NjQsnTsCg71HxVsL3jM:b-ghqbjm) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/worker/tests/local_worker_test.rs#L305)):*
> ```XML
>             },
>             skip_cache_lookup: true,
>             digest_function: DigestHasherFunc::Sha256,
> ```

Note: Not for this commit, but we should look into a way to make tests parametric. This way we could "matrix-test" stuff like this.
___
*[`config/cas_server.rs` line 550 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQtWdv7QLcg1ZJj06T:-NjQtWdv7QLcg1ZJj06U:b6pn1f) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/config/cas_server.rs#L550)):*
> ```XML
>     /// by client.
>     ///
>     /// Default: ConfigDigestHashFunction::Sha256
> ```

Nit: I vote for making Blake3 the default and make users set sha2 if they want 15x slower hashing :smiling_imp: 
___
*[`util/digest_hasher.rs` line 90 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQuIv5-3rBKrkaqfpM:-NjQuIv5-3rBKrkaqfpN:b9u1iz5) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/util/digest_hasher.rs#L90)):*
> ```XML
>             )),
>         }
>     }
> ```

4 variations of `From`/`TryFrom` seems overkill.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/403)* status: all files reviewed, 5 unresolved discussions (waiting on @aaronmondal)

___
*[`cas/cas_main.rs` line 646 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQr2zxAmJBYxIIH8kn:-NjSpFJd8WNcx5j02BAP:b-my9eul) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/cas_main.rs#L646)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I wonder whether we'd want to make blake3 the default here. I'm aware that bazel defaults to SHA2 (and blake3 support was only just added in 6.4), but this would force users to explicitly set `sha2` in their config. Considering that blake3 is ~15x faster than SHA2 this seems reasonable to me to make users think twice whether they actually want to keep using the significantly slower SHA2.
</blockquote></details>

I would rather trade ease of use in exchange for slower builds.

Bazel and buck2 are the only clients that support blake3 to my knowledge and Bazel requires a command line argument to enable it.

Also, most companies cannot just upgrade bazel at any time, it's a big deal to go through an upgrade.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/403)* status: all files reviewed, 5 unresolved discussions (waiting on @aaronmondal)

___
*[`cas/scheduler/tests/utils/scheduler_utils.rs` line 42 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsB-i8LISEwb634c0:-NjSpgOc1lycsbXENHc4:b-jpjzat) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/scheduler/tests/utils/scheduler_utils.rs#L42)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this intentionally hardcoded?
</blockquote></details>

Yes, its a test util.
___
*[`cas/worker/tests/local_worker_test.rs` line 216 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsbsr4BIIhjLJ5OuY:-NjSpn6v-lU6K0uzUcvL:bfyhi18) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/worker/tests/local_worker_test.rs#L216)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Will this still work on Windows?
</blockquote></details>

It should, Unix timestamps are supported on windows.
___
*[`cas/worker/tests/local_worker_test.rs` line 305 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQsnTsCg71HxVsL3jL:-NjSq-V8-arRMWlPRGdR:boz7az4) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/worker/tests/local_worker_test.rs#L305)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Note: Not for this commit, but we should look into a way to make tests parametric. This way we could "matrix-test" stuff like this.
</blockquote></details>

I thought of that but was worried of the complexity it'd introduce and difficulty to debug.

Id use integration tests to validate entire  builds to for matrix-like tests.
___
*[`config/cas_server.rs` line 550 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQtWdv7QLcg1ZJj06T:-NjSqNdb-IdAcfGZBQIY:b-u11dvs) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/config/cas_server.rs#L550)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Nit: I vote for making Blake3 the default and make users set sha2 if they want 15x slower hashing :smiling_imp:
</blockquote></details>

but then most clients wont work.

Remember there is a capabilities property that tells the client we support blake3. the client can choose whatever. This is only used when none is specified.
___
*[`util/digest_hasher.rs` line 90 at r3](https://reviewable.io/reviews/TraceMachina/turbo-cache/403#-NjQuIv5-3rBKrkaqfpM:-NjSqvRP7ZnRrOw9m5vx:b-7q81wo) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/util/digest_hasher.rs#L90)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

4 variations of `From`/`TryFrom` seems overkill.
</blockquote></details>

I was trying to hide complexity here. Otherwise some places will need to define the complexity where the `.into()`/`.from()` is called.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/403)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/worker/tests/local_worker_test.rs` line 34 at r3](https://reviewable.io/reviews/tracemachina/native-link/403#-NjYj54dA3KKDET-DHjc:-NjYj54dA3KKDET-DHjd:b-js5pen) ([raw file](https://github.com/tracemachina/native-link/blob/9a0899e3e930fe45a28e4c132438cdb0d20213f8/cas/worker/tests/local_worker_test.rs#L34)):*
> ```XML
> use action_messages::{ActionInfo, ActionInfoHashKey, ActionResult, ActionStage, ExecutionMetadata};
> use common::{encode_stream_proto, fs, DigestInfo};
> use config::cas_server::{LocalWorkerConfig, WrokerProperty};
> ```

`WorkerProperty` is correct. This was previously changed in #390

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/403#-:-Njf2QCLC6qNmYKJjosx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
