### PR TITLE
Refactor ExistanceStore

### PR DESCRIPTION
**Pull request by allada**
Refactor Existance Store to be compatible with store API.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418#-:-NkD1z7m7nhru6MK8L1V:b-c0aesp)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @blakehatch)

**Review by blakehatch — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418#-:-NkDAdv4CMfJ2mUb7cqA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`native-link-store/src/existence_store.rs` line 88 at r1](https://reviewable.io/reviews/TraceMachina/native-link/418#-NkD6kld8fMoCSk-tK4q:-NkD6kld8fMoCSk-tK4r:b-wjclz9) ([raw file](https://github.com/TraceMachina/native-link/blob/04a11abeec1d805f71659433c1411a8e5708a655/native-link-store/src/existence_store.rs#L88)):*
> ```XML
>         self.pin_inner()
>             .has_with_results(&not_cached_digests, &mut inner_results)
>             .await?;
> ```

Nit: `.err_tip(|| "In ExistenceStore::inner_has_with_results")` 
___
*[`native-link-util/src/evicting_map.rs` line 33 at r1](https://reviewable.io/reviews/TraceMachina/native-link/418#-NkDAEy0AncYO9AVioLU:-NkDAEy0AncYO9AVioLV:b-ksis0u) ([raw file](https://github.com/TraceMachina/native-link/blob/7f406968e256c5e1b262b992b23400a8cd977241/native-link-util/src/evicting_map.rs#L33)):*
> ```XML
> #[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
> pub struct SerializedLRU {
>     pub data: Vec<(DigestInfo, i32)>,
> ```

Nit: Is there a way to use evicting_map for it's pruning capabilities without having to store any data as existence is just being checked? Probably an over-optimization especially since this approach limits the size of the data stored and by extension the upside of an optimization like this but something to consider.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`native-link-util/src/evicting_map.rs` line 33 at r1](https://reviewable.io/reviews/TraceMachina/native-link/418#-NkDAEy0AncYO9AVioLU:-NkDJYJo4NOcU3hRmLwb:bomzd39) ([raw file](https://github.com/TraceMachina/native-link/blob/7f406968e256c5e1b262b992b23400a8cd977241/native-link-util/src/evicting_map.rs#L33)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Nit: Is there a way to use evicting_map for it's pruning capabilities without having to store any data as existence is just being checked? Probably an over-optimization especially since this approach limits the size of the data stored and by extension the upside of an optimization like this but something to consider.
</blockquote></details>

Storing a `()` (ie: void) costs 1 byte (in C, so probably the same in rust), so the overhead is so small it is negligible. 

Long answer: Yes, but it would be a pain to refactor and use.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @blakehatch)

___
*[`native-link-store/src/existence_store.rs` line 88 at r1](https://reviewable.io/reviews/TraceMachina/native-link/418#-NkD6kld8fMoCSk-tK4q:-NkDK3Oq6ptmKenYuYaV:b-896fix) ([raw file](https://github.com/TraceMachina/native-link/blob/04a11abeec1d805f71659433c1411a8e5708a655/native-link-store/src/existence_store.rs#L88)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Nit: `.err_tip(|| "In ExistenceStore::inner_has_with_results")`
</blockquote></details>

Done.

**Review by blakehatch — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
