### PR TITLE
Added README to docker-compose deployment-example

### LINKED ISSUE #425: Docker-Compose README
Currently, there is not README for the docker-compose directory. There should be one.

### PR DESCRIPTION
**Pull request by blakehatch**
# Description
Added README for Docker-Compose deployment example covering setup, configuration, notes & tips.

Fixes #425

## Type of change
-[x] Documentation Update

## Checklist
- [x] Updated documentation if needed

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
LGTM content-wise :+1: 

If you're using the nix flake+direnv it should automatically remove bad newlines and trailing whitespace for you on commit.

You can also set `markdownlint.enable = true;` in the `tools/pre-commit-hooks.nix` file. When you then enter the flake it'll set up markdownlint as pre-commit hook so that you get all the `nit`s i posted on commit check.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427#-:-NkP3RWg8QT0BJ0yBiof:btu909x)* status: all files reviewed, 19 unresolved discussions (waiting on @blakehatch and @MarcusSorealheis)

___
*[`deployment-examples/docker-compose/README.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2NA-2f1J5vvs9Bsc:-NkP2NA06Q0zaZUS4XJy:b8z10t8) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L1)):*
> ```Markdown
> # Native Link's Docker Compose Deployment
> ```

nit: There should be an empty line between headers and content.
___
*[`deployment-examples/docker-compose/README.md` line 4 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2V1e1eR-xigSUocO:-NkP2V1e1eR-xigSUocP:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L4)):*
> ```Markdown
> This directory contains a reference/starting point on creating a full Docker Compose deployment of Native Link's cache and remote execution system.
> 
> ## Docker Setup
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 6 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP1FsPEFgEyyQOKF87:-NkP1FsPEFgEyyQOKF88:b-k06tfa) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L6)):*
> ```Markdown
> ## Docker Setup
> 1. Ensure [Docker](https://docs.docker.com/engine/install/) and [Docker Compose](https://docs.docker.com/compose/install/) are installed on your system.
> 2. Open terminal and navigate to this directory.
> ```

`a terminal`
___
*[`deployment-examples/docker-compose/README.md` line 9 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2YLpDQ2UGoZnFvCW:-NkP2YLpDQ2UGoZnFvCX:b-yauexz) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L9)):*
> ```Markdown
> 3. Run `docker-compose up -d` to start the services.
> 
> It will take some time to apply, when it is finished everything should be running. The endpoints are:
> ```

nit: Code blocks should be surrounded by empty lines.
___
*[`deployment-examples/docker-compose/README.md` line 10 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2dM_CFOC-EZMVF-R:-NkP2dM_CFOC-EZMVF-S:bhylc56) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L10)):*
> ```Markdown
> 
> It will take some time to apply, when it is finished everything should be running. The endpoints are:
> ```
> ```

"Language anonymous" code blocks should still specify `txt` or some other language that makes things look pretty.
___
*[`deployment-examples/docker-compose/README.md` line 16 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2q6s4cl1OrbIJiu9:-NkP2q6s4cl1OrbIJiuA:by02qvv) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L16)):*
> ```Markdown
> 
> As a reference you should be able to compile this project using bazel with something like:
> ```sh
> ```

nit: Missing empty line
___
*[`deployment-examples/docker-compose/README.md` line 24 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2stQAqy5p4FcjPTX:-NkP2stQAqy5p4FcjPTY:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L24)):*
> ```Markdown
> ```
> 
> ## Instances
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 25 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP1Zw69LwMUe2oO_37:-NkP1Zw69LwMUe2oO_38:bzib7cz) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L25)):*
> ```Markdown
> 
> ## Instances
> All instances use the same Docker image, trace_machina/native-link:latest, built from the Dockerfile located at ./deployment-examples/docker-compose/Dockerfile.
> ```

Rewiewable is displaying this and some the next section in cursive. Maybe there are some backticks missing somewhere?
___
*[`deployment-examples/docker-compose/README.md` line 27 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2wD86YTlOGUtyI9k:-NkP2wD86YTlOGUtyI9l:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L27)):*
> ```Markdown
> All instances use the same Docker image, trace_machina/native-link:latest, built from the Dockerfile located at ./deployment-examples/docker-compose/Dockerfile.
> 
> ### CAS
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 28 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP2Bzi8RbbXiibM2SG:-NkP2Bzi8RbbXiibM2SH:b-rqg8kw) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L28)):*
> ```Markdown
> 
> ### CAS
> The CAS (Content Addressable Storage) service is used as a local cache for the Native Link system. It is configured in the docker-compose.yml file under the native_link_local_cas service.
> ```

Cursive here as well. Might be a bug in reviewable or bad backticks somewhere.
___
*[`deployment-examples/docker-compose/README.md` line 45 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP1sahB-skTlO36xs-:-NkP1sai4bTugrZhRvIs:bd2o0ws) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L45)):*
> ```Markdown
>     environment:
>       RUST_LOG: ${RUST_LOG:-warn}
>     ports: [ "50051:50051/tcp", "127.0.0.1:50061:50061", "50071:50071/tcp", ]
> ```

nit: Let's put these in separate lines for readability:
```
[
  "50051:50051/tcp",
  "127.0.0.1:50061:50061",
  "50071":50071/tcp",
]
```
___
*[`deployment-examples/docker-compose/README.md` line 50 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP38u--pmfJ5CbNPUR:-NkP38u--pmfJ5CbNPUS:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L50)):*
> ```Markdown
> ```
> 
> ### Scheduler
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 52 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3APcCcJN-lVyCbrQ:-NkP3APcCcJN-lVyCbrR:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L52)):*
> ```Markdown
> ### Scheduler
> The scheduler is currently the only single point of failure in the system. We currently only support one scheduler at a time.
> The scheduler service is responsible for scheduling tasks in the Native Link system. It is configured in the docker-compose.yml file under the native_link_scheduler service.
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 74 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3D6v7X7yTAnmGfNN:-NkP3D6v7X7yTAnmGfNO:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L74)):*
> ```Markdown
> ```
> 
> ### Workers
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 76 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3F3A7qg15KEWOUB0:-NkP3F3A7qg15KEWOUB1:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L76)):*
> ```Markdown
> ### Workers
> Worker instances are responsible for executing tasks. They are configured in the docker-compose.yml file under the native_link_executor service.
> ```
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 98 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3MDM1PELdz21PMjw:-NkP3MDM1PELdz21PMjx:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L98)):*
> ```Markdown
> ```
> 
> ## Security
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 105 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3Nkp9MX86waMBYvL:-NkP3Nkp9MX86waMBYvM:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L105)):*
> ```Markdown
> If you decide to stop using this setup, you can use `docker-compose down` to stop and remove all the containers. However, in a non-local setup, additional steps may be required to ensure that all data is securely deleted.
> 
> ## Future work / TODOs
> ```

nit: Missing empty line.
___
*[`deployment-examples/docker-compose/README.md` line 109 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP3P9Y5fsAKxzAkC0f:-NkP3P9Y5fsAKxzAkC0g:b-bebo5p) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L109)):*
> ```Markdown
> The Docker Compose setup does not automatically delete old data. This could be implemented with a cleanup service or script.
> 
> ## Useful tips
> ```

nit: Missing empty line.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427)* status: all files reviewed, 21 unresolved discussions (waiting on @blakehatch and @MarcusSorealheis)

___
*[`deployment-examples/docker-compose/README.md` line 6 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkLvhK75BPE95W1cw8-:-NkLvhK75BPE95W1cw80:b-4bfp71) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L6)):*
> ```Markdown
> ## Docker Setup
> 1. Ensure [Docker](https://docs.docker.com/engine/install/) and [Docker Compose](https://docs.docker.com/compose/install/) are installed on your system.
> 2. Open terminal and navigate to this directory.
> ```

nit: Combine 2 and 3. This line is obvious and directly relates to what happens in 3
___
*[`deployment-examples/docker-compose/README.md` line 11 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkLw1MH0-YEMjZv4aPS:-NkLw1MH0-YEMjZv4aPT:b-vdlenc) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L11)):*
> ```Markdown
> It will take some time to apply, when it is finished everything should be running. The endpoints are:
> ```
> CAS/AC: 0.0.0.0:50051/50071
> ```

nit: Separate these two and explain the different ports.

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427)* status: all files reviewed, 22 unresolved discussions (waiting on @aaronmondal and @blakehatch)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkTmA4F1KEZ7-P10E9i):*
Nit:  The commit is living on so I prefer `Adds` to beginning a commit message with a past participle. 
___
*[`deployment-examples/docker-compose/README.md` line 45 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkP1sahB-skTlO36xs-:-NkTn45t5B1v7OqwNtvD:bqog80t) ([raw file](https://github.com/TraceMachina/native-link/blob/539cfcd784584f8c92b7e20d45187eff3f57d7d8/deployment-examples/docker-compose/README.md#L45)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Let's put these in separate lines for readability:
```
[
  "50051:50051/tcp",
  "127.0.0.1:50061:50061",
  "50071":50071/tcp",
]
```
</blockquote></details>

Agreed

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427#-:-NkTnDeD8W7DqyaHxa3t:bnfp4nl)* status: all files reviewed, 22 unresolved discussions (waiting on @aaronmondal and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/427)* status: all files reviewed, 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/native-link/427#-NkTmA4F1KEZ7-P10E9i):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Note that Git's recommendation is present tense, imperative mood: https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?h=v2.36.1#n181

Apart from being a somewhat official recommendation it's also usually the shortest form (`Add` vs `AddS` vs `AddED`). We don't have this documented though, so we can't really expect/enforce this at the moment. In any case we should set a standard for this.

**Pull request merged**
