### PR TITLE
Rewrite the build infrastructure

### PR DESCRIPTION
**Pull request by aaronmondal**
Our previous build layout was fairly custom and hard to maintain.
Migrate to a more standards-conform layout that is compatible with good
Cargo and Bazel practices and feels natural to develop in.

This commit swaps the previous "one-crate-per-file" layout to a layout
where we have a few medium sized crates that are just fine-grained
enough to allow almost the same amount of parallelization as the
previous fine-grained layout.

The new layout enables dependency auto-updaters, standard cargo tooling
and doc autogeneration. This should improve DX quite a bit and gives us
some much needed compatibility with nix/cargo interop and should make
most standard cargo extensions compatible with the repository.

Some notable changes to the file layout:

- The previous `error` crate is no longer part of `utils`. It is now a
  standalone module. This was necessary to keep macro exports compatible
  with the Cargo build.
- The old `scheduler.rs` file is now split into `action_scheduler.rs`
  and `worker_scheduler.rs` since we don't want imports like
  `native_link_scheduler::scheduler`.
- Some tests now use a slightly different import mechanism for test-only
  dependencies.
- The store traits are now in `native_link_utils`, as it was used
  virtually everywhere. Moving this up in the dependency graph allows
  for higher parallelization of the other crates.

Added documentation targets for every crate (except the `cas` binary
itself, as this will require a dedicated commit). These doc targets can
be viewed by pointing a browser to
`bazel-bin/thetarget.rustdoc/thetarget/index.html`.

Added rustfmt configuration to standardize imports. We now use `crate::`
syntax which plays well with rusfmts's import formatting. The new layout
makes it easier to spot crate/directory interdependencies so the we can
remove those in future commits.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/394)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
Could you update this PR and lets get it landed?

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394#-:-Njisy_S2sX7kpgGQ64r:by1sq7v)* status: 0 of 202 files reviewed, all discussions resolved (waiting on @blakehatch and @MarcusSorealheis)

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 98 of 202 files at r1, 13 of 108 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394)* status: 111 of 213 files reviewed, 9 unresolved discussions (waiting on @aaronmondal, @blakehatch, and @MarcusSorealheis)

___
*[`BUILD.bazel` line 11 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkVvOa-2opLEMrjirK:-NjkVvOa-2opLEMrjirL:bb77qhl) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/BUILD.bazel#L11)):*
> ```Starlark
> 
> exports_files(
>     glob(["src/**", "tests/**"]) + [
> ```

nit: Lets list every file.
___
*[`BUILD.bazel` line 22 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkVz2-8tvxZ80nFiup:-NjkVz2-8tvxZ80nFiuq:bb77qhl) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/BUILD.bazel#L22)):*
> ```Starlark
>     name = "native_link",
>     srcs = glob(
>         include = ["src/**/*.rs"],
> ```

nit: Lets list every file.
___
*[`BUILD.bazel` line 100 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkW-UQ-3WtetGYUgzy:-NjkW-UQ-3WtetGYUgzz:bb77qhl) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/BUILD.bazel#L100)):*
> ```Starlark
> rust_test_suite(
>     name = "native_link_tests",
>     srcs = glob(["tests/*.rs"]),
> ```

nit: Lets list every file.
___
*[`Cargo.toml` line 7 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkW6gg9AIRMT7slCWw:-NjkW6gg9AIRMT7slCWx:b-xbuldp) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/Cargo.toml#L7)):*
> ```TOML
> 
> [workspace]
> resolver = "2"
> ```

Do we need this now?
___
*[`src/config.rs` line 1 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkWq-F52napcjMq_fp:-NjkWq-F52napcjMq_fq:bok2db8) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/config.rs#L1)):*
> ```XML
> pub mod cas_server;
> ```

nit: Needs copyright.
___
*[`src/grpc_service.rs` line 1 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkX2jE3ncjcJ_yRViO:-NjkX2jE3ncjcJ_yRViP:bok2db8) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/grpc_service.rs#L1)):*
> ```XML
> pub mod ac_server;
> ```

nit: Needs copyright.
___
*[`src/lib.rs` line 1 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkX4Yv6Vyf3GgCmVM8:-NjkX4Yv6Vyf3GgCmVM9:bok2db8) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/lib.rs#L1)):*
> ```XML
> pub mod config;
> ```

nit: Needs copyright.
___
*[`src/scheduler.rs` line 1 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkX5HJEeqqsriGUoTS:-NjkX5HJEeqqsriGUoTT:bok2db8) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/scheduler.rs#L1)):*
> ```XML
> pub mod action_messages;
> ```

nit: Needs copyright.
___
*[`src/store.rs` line 15 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkXAXeAb3PgxRvnve9:-NjkXAXeAb3PgxRvnveA:bvwyo8y) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/store.rs#L15)):*
> ```XML
> // limitations under the License.
> 
> pub mod ac_utils;
> ```

yuck, can we somehow use `crate::` instead?

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394)* status: 111 of 213 files reviewed, 10 unresolved discussions (waiting on @aaronmondal, @blakehatch, and @MarcusSorealheis)

___
*[`BUILD.bazel` line 74 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkXY2cCQGGWVDIfcuW:-NjkXY2dCnzaCbyFFtWK:b-palfyi) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/BUILD.bazel#L74)):*
> ```Starlark
> 
> rust_binary(
>     name = "nlink",
> ```

Lets not rename this yet, we will do it in a follow up PR. Because there's things like terraform that will likely break.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394)* status: 104 of 214 files reviewed, 3 unresolved discussions (waiting on @allada, @blakehatch, and @MarcusSorealheis)

___
*[`BUILD.bazel` line 74 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkXY2cCQGGWVDIfcuW:-Njl1HlC6B2Yw1U05Nmc:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/BUILD.bazel#L74)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets not rename this yet, we will do it in a follow up PR. Because there's things like terraform that will likely break.
</blockquote></details>

Done.
___
*[`Cargo.toml` line 7 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkW6gg9AIRMT7slCWw:-Njl1Jnb0bsh-5F54Pwn:b-id3ns4) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/Cargo.toml#L7)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Do we need this now?
</blockquote></details>

Unfortunately yes. Both the Bazel resolver and nix cargo wrappers need this workspace for some reason. The `resolver = "2"` line is technically redundant and we could remove that. I think  there was some issue I can't remember where it was recommended to make the resover version explicit.
___
*[`src/store.rs` line 15 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkXAXeAb3PgxRvnve9:-Njl1uoMC-q0wjw5SpKY:becprkx) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/store.rs#L15)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

yuck, can we somehow use `crate::` instead?
</blockquote></details>

I removed the rest of the actual code from here and put it in a `store_manager` subcrate. The amount of files here is a bit much, but I'd say this is more of a "not hiding anything" type of thing. Arguably quite ugly, but this gives us very explicit import paths that (in conjunction with the now ordered imports in every file) make it much easier to see where we could reduce interdependencies and split this into sensible smaller crates.

There are a few alternatives to the `thing.rs`/`thing` directory approach, but this seems to be the current "recommended" way of doing things and it's at least better than the `mod.rs` approach where literally every file in the repo would just be called `mod.rs` :rofl: 

As a side note, a benefit of this explicit `pub mod` approach is that it makes it quite easy to turn features on and off by using markers like `#[cfg(feature = "s3")]`.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394)* status: 104 of 214 files reviewed, 3 unresolved discussions (waiting on @allada, @blakehatch, and @MarcusSorealheis)

___
*[`src/store.rs` line 15 at r2](https://reviewable.io/reviews/tracemachina/native-link/394#-NjkXAXeAb3PgxRvnve9:-Njl3zFl7TAj_60GTr4c:b1t9htq) ([raw file](https://github.com/tracemachina/native-link/blob/33b1d29a9588a28861c721445b50575e87a55b42/src/store.rs#L15)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I removed the rest of the actual code from here and put it in a `store_manager` subcrate. The amount of files here is a bit much, but I'd say this is more of a "not hiding anything" type of thing. Arguably quite ugly, but this gives us very explicit import paths that (in conjunction with the now ordered imports in every file) make it much easier to see where we could reduce interdependencies and split this into sensible smaller crates.

There are a few alternatives to the `thing.rs`/`thing` directory approach, but this seems to be the current "recommended" way of doing things and it's at least better than the `mod.rs` approach where literally every file in the repo would just be called `mod.rs` :rofl: 

As a side note, a benefit of this explicit `pub mod` approach is that it makes it quite easy to turn features on and off by using markers like `#[cfg(feature = "s3")]`.
</blockquote></details>

Actually, when I think about it, this pattern might be better than I initially thought. With the right code layout,`thing.rs` can act as the public API interface (think exposed header in C++ land) while all the files in the `thing` directory act as implementation details. In that case we'd not have the `pub mod` lines anymore and instead have a seemingly very clean interface where `thing.rs` contains the entire public API for a crate and everything else can be ignored by users. This would also make it easy to spot API changes since one only needs to look at history of the `thing.rs` file.

**Comment by aaronmondal** [comment]
FYI @allada In case you're wondering why the new targets are `native-link-something` and not `native_link_somethin` as is usually done in Bazel, this is because the dashes make it easier to distinguish build targets and crate names when grepping and it allows shell completion for targets like `bazel build native-<TAB>`

Also note that all the test targets are just called `integration` because the `rust_test_suite` automatically appends the `_tests` string and it looks nicer in the terminal this way.

**Review by allada — APPROVED** [review]
:lgtm:

All the details we can fight another day.

> Reviewed 4 of 202 files at r1, 2 of 108 files at r2, 1 of 1 files at r4, 119 of 119 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394#-:-NjuEkST4jQ3_oZGF1B4:beypg9w)* status: all files reviewed, 22 unresolved discussions (waiting on @aaronmondal, @blakehatch, and @MarcusSorealheis)

___
*[`native-link-service/tests/ac_server_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCA8NDet52cz71RsW:-NjuCA8NDet52cz71RsX:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-service/tests/ac_server_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-service/tests/bytestream_server_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCECJB-OJFjHMZTUk:-NjuCECJB-OJFjHMZTUl:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-service/tests/bytestream_server_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-service/tests/cas_server_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCIxg5BJC1FYQAmCh:-NjuCIxg5BJC1FYQAmCi:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-service/tests/cas_server_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/ac_utils_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCrBX84S67YGvDiZM:-NjuCrBYE1XSMuBgRN7U:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/ac_utils_test.rs#L1)):*
> ```XML
> // Copyright 2023 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/compression_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCslm0R_oZMvxz4sp:-NjuCslm0R_oZMvxz4sq:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/compression_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/dedup_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCua-4dKQItI6SLlh:-NjuCua-4dKQItI6SLli:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/dedup_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/fast_slow_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCxTw8x_aw8CxZqlZ:-NjuCxTw8x_aw8CxZql_:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/fast_slow_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/filesystem_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuCz548I6B6K1pDI4s:-NjuCz548I6B6K1pDI4t:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/filesystem_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/memory_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuD03zCxCGw-YQKZ4s:-NjuD03zCxCGw-YQKZ4t:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/memory_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/ref_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuD1Uq-OYfHiOi4Sum:-NjuD1Uq-OYfHiOi4Sun:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/ref_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/shard_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuD5KK5tBAJRUDvkWK:-NjuD5KK5tBAJRUDvkWL:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/shard_store_test.rs#L1)):*
> ```XML
> // Copyright 2023 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/size_partitioning_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuD6kY7orXtmb80D1T:-NjuD6kY7orXtmb80D1U:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/size_partitioning_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-store/tests/verify_store_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuD89C2uVAD0nIZFuH:-NjuD89C2uVAD0nIZFuI:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-store/tests/verify_store_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/async_fixed_buffer_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDMCEELgNTkpZFDEt:-NjuDMCEELgNTkpZFDEu:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/async_fixed_buffer_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/buf_channel_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDNMc7tdUeqPrMH09:-NjuDNMc7tdUeqPrMH0A:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/buf_channel_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/evicting_map_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDOOR8R5XCBk4R58F:-NjuDOOR8R5XCBk4R58G:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/evicting_map_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/fastcdc_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDPMd5f49oc8qa2pj:-NjuDPMd5f49oc8qa2pk:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/fastcdc_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/fs_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDQh6EZ4x_SUM4lSj:-NjuDQh6EZ4x_SUM4lSk:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/fs_test.rs#L1)):*
> ```XML
> // Copyright 2023 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/resource_info_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDRov2sFqKh4botWq:-NjuDRov2sFqKh4botWr:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/resource_info_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-util/tests/retry_test.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDSd32nXtlXK1nThy:-NjuDSd32nXtlXK1nThz:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-util/tests/retry_test.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-worker/tests/utils/local_worker_test_utils.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDjPf9U0zxwi0D94y:-NjuDjPf9U0zxwi0D94z:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-worker/tests/utils/local_worker_test_utils.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.
___
*[`native-link-worker/tests/utils/mock_running_actions_manager.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/native-link/394#-NjuDkakCibrtPTS2w9J:-NjuDkakCibrtPTS2w9K:bwzsymu) ([raw file](https://github.com/tracemachina/native-link/blob/1a9bfecbe05573df6904d8af7321a29c656d2966/native-link-worker/tests/utils/mock_running_actions_manager.rs#L1)):*
> ```XML
> // Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

nit: Wrong name.

**Review by aaronmondal — COMMENTED** [review]
:partying_face: 

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/394#-:-NjuNSwj44Xcz4er_7Uo:b-ra0xjj)* status: 161 of 239 files reviewed, all discussions resolved (waiting on @allada, @blakehatch, and @MarcusSorealheis)

**Pull request merged**
