### PR TITLE
Fix the incorrect config path in the documentation

### LINKED ISSUE #415: Fix the incorrect config path in the documentation
After the [rewrite of the build infrastructure](https://github.com/TraceMachina/native-link/commit/3147265047544572e3483c985e4aab0f9fdded38), all path problems are resolved successfully in code files.
But we missed some of them in the documentation.

Updating documentation needs to be done since it needs to be read by users.

Here are missed ones.

- `./README.md`

  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/README.md?plain=1#L38
  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/README.md?plain=1#L48
  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/README.md?plain=1#L110

- `./native-link-config/README.md`

  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/native-link-config/README.md?plain=1#L6
  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/native-link-config/README.md?plain=1#L13

- `./proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto`

  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto#L88

- `./proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs`

  https://github.com/TraceMachina/native-link/blob/3147265047544572e3483c985e4aab0f9fdded38/proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs#L45

### PR DESCRIPTION
**Pull request by steed924**
# Description

After the [rewrite of the build infrastructure](https://github.com/TraceMachina/native-link/commit/3147265047544572e3483c985e4aab0f9fdded38), all path problems are resolved successfully in code files.
But we missed some of them in the documentation.

Updating documentation needs to be done since it needs to be read by users.
Those documentation issues are fixed.

Fixes #415 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/416)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/416)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @steed924)

___
*[`proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto` line 88 at r1](https://reviewable.io/reviews/TraceMachina/native-link/416#-NjwtfX75m9_QpEU80iC:-NjwtfX82y6s_q-Ea6E4:bfx9xhr) ([raw file](https://github.com/TraceMachina/native-link/blob/2c1a098574c2f9cbceca6150353eea31147ad761/proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto#L88)):*
> ```proto
>     ///
>     /// The details on how to use this property can be found here:
>     /// https://github.com/tracemachina/native-link/blob/master/native-link-config/src/cas_server.rs
> ```

nit: We need to pin the hash or else the code can change and make this comment link not work.
___
*[`proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs` line 45 at r1](https://reviewable.io/reviews/TraceMachina/native-link/416#-NjwtleG5adpV5ZrLoPk:-NjwtleHC1Vd7ief-QI5:b-rqxvo7) ([raw file](https://github.com/TraceMachina/native-link/blob/2c1a098574c2f9cbceca6150353eea31147ad761/proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs#L45)):*
> ```XML
>     /// /
>     /// / The details on how to use this property can be found here:
>     /// / <https://github.com/tracemachina/native-link/blob/master/native-link-config/src/cas_server.rs>
> ```

ditto.

**Review by steed924 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/416)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto` line 88 at r1](https://reviewable.io/reviews/TraceMachina/native-link/416#-NjwtfX75m9_QpEU80iC:-Njx1igT5ywICtQQCP-k:bb7f2mf) ([raw file](https://github.com/TraceMachina/native-link/blob/2c1a098574c2f9cbceca6150353eea31147ad761/proto/com/github/trace_machina/native_link/remote_execution/worker_api.proto#L88)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: We need to pin the hash or else the code can change and make this comment link not work.
</blockquote></details>

done
___
*[`proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs` line 45 at r1](https://reviewable.io/reviews/TraceMachina/native-link/416#-NjwtleG5adpV5ZrLoPk:-Njx1kem8-2yl_6OXt8N:bb7f2mf) ([raw file](https://github.com/TraceMachina/native-link/blob/2c1a098574c2f9cbceca6150353eea31147ad761/proto/genproto/com.github.trace_machina.native_link.remote_execution.pb.rs#L45)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

done

**Review by aaronmondal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/416)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

**Review by MarcusSorealheis — APPROVED** [review]
LGTM.  I wonder if we should one day maintain a `jsonc` file that is a copy of all the `json` files. That way, we dan have one representation that is comment compatible so that our users do not need to edit the JSON but can still understand the reference `jsonc`'s.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/416#-:-Nk2Kjt_C02877d_9xNk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @steed924)

**Pull request merged**
