### PR TITLE
Add Noop store

### LINKED ISSUE #385: Implement Noop store
We need a store that sends the data to the void and always returns 404 (not found) on a `.has()` and `.get()` requests.

An example where this store will be useful:
```json5
{
  "fast_slow": {
    "fast": {
      "size": 2097152,
      "lower_store": {
        "memory": {
          "max_bytes": 100000000
        }
      },
      "upper_store": {
        "noop": {} // <-- Noop store here, send data to void.
      }
    },
    "slow": {
      "s3_store": {
        "region": "us-west-1",
        "bucket": "some-bucket"
      }
    }
  }
}
```

This config will:
* Read data from memory first, if the data is greater than 2MB immediately return `NotFound`
* Read data from s3 store if not found in memory store or greater than 2MB.
* Write data to memory store only if less than 2MB.
* Always write to s3 store.

### PR DESCRIPTION
**Pull request by allada**
Adds a Noop Store that sends data to the void and always returns 404 (NotFound).

closes #385

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/408)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@aaronmondal 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/408#-:-NjY6PGK7di_paQjQmW-:b-p12xwa)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by aaronmondal — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/408)* status: all files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`config/examples/basic_cas.json` line 18 at r1](https://reviewable.io/reviews/tracemachina/native-link/408#-NjYbEwZ4-K5kZEUuSTn:-NjYbEwZ4-K5kZEUuSTo:bu4je9w) ([raw file](https://github.com/tracemachina/native-link/blob/f989e612715a7fe645e69c4c78a50e9b7262ad17/config/examples/basic_cas.json#L18)):*
> ```JSON
>           "filesystem": {
>             "content_path": "/tmp/turbo_cache/data-worker-test/content_path-cas",
>             "temp_path": "/tmp/turbo_cache/data-worker-test/tmp_path-cas",
> ```

nit: `native_link`
___
*[`config/examples/basic_cas.json` line 70 at r1](https://reviewable.io/reviews/tracemachina/native-link/408#-NjYb6nqCZWcnbZQ_x9N:-NjYb6nqCZWcnbZQ_x9O:bu4je9w) ([raw file](https://github.com/tracemachina/native-link/blob/f989e612715a7fe645e69c4c78a50e9b7262ad17/config/examples/basic_cas.json#L70)):*
> ```JSON
>         "ac_store": "AC_MAIN_STORE",
>       },
>       "work_directory": "/tmp/turbo_cache/work",
> ```

nit: `native_link`

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/408)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @aaronmondal)

___
*[`config/examples/basic_cas.json` line 18 at r1](https://reviewable.io/reviews/tracemachina/native-link/408#-NjYbEwZ4-K5kZEUuSTn:-NjZbh3P7x516aSaVxpG:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/f989e612715a7fe645e69c4c78a50e9b7262ad17/config/examples/basic_cas.json#L18)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: `native_link`
</blockquote></details>

Done.
___
*[`config/examples/basic_cas.json` line 70 at r1](https://reviewable.io/reviews/tracemachina/native-link/408#-NjYb6nqCZWcnbZQ_x9N:-NjZbikgEtNg-IkZaEUP:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/f989e612715a7fe645e69c4c78a50e9b7262ad17/config/examples/basic_cas.json#L70)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: `native_link`
</blockquote></details>

Done.

**Review by aaronmondal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/408)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
