### PR TITLE
Migrate logs to tracing

### PR DESCRIPTION
**Pull request by aaronmondal**
For now just swap out the crate. An example of idiomatic usage is in `cas/grpc_service/ac_server.rs`. Future commits can build on this and extend the tracing and subscriber logic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/387)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: 0 of 48 files reviewed, 1 unresolved discussion (waiting on @aaronmondal and @blakehatch)

___
*[`util/common.rs` line 27 at r1](https://reviewable.io/reviews/tracemachina/native-link/387#-Nji8j5B3pARAHL645XN:-Nji8j5B3pARAHL645XO:b-f3y33s) ([raw file](https://github.com/tracemachina/native-link/blob/cf5f45b3a6762cdd607e0a009fbff29615b478e1/util/common.rs#L27)):*
> ```XML
> pub use fs;
> use hex::FromHex;
> pub use log;
> ```

Can we re-export the `tracing` common functions/macros here so we don't need to import the external `tracing` library everywhere?

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: 0 of 48 files reviewed, 1 unresolved discussion (waiting on @allada and @blakehatch)

___
*[`util/common.rs` line 27 at r1](https://reviewable.io/reviews/tracemachina/native-link/387#-Nji8j5B3pARAHL645XN:-Nji9KNi1WEnJ2hRy4O5:b-l8l05w) ([raw file](https://github.com/tracemachina/native-link/blob/cf5f45b3a6762cdd607e0a009fbff29615b478e1/util/common.rs#L27)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we re-export the `tracing` common functions/macros here so we don't need to import the external `tracing` library everywhere?
</blockquote></details>

I'm trying to reduce reexports like this as much as possible to increase potential for build parallelization. For instance, `common.rs` depends on `proto`, so if we depend on `common` in a downstream file because we only need the `tracing` functionality (which is the case for quite a few files) its build will be blocked until `proto` is available.

I think it's better to keep imports as shallow as possible as every reexport creates a potential bottleneck target.

**Review by allada — COMMENTED** [review]
Sorry, there was a lot going on and this one fell through. Can you rebase and I'll do a review. Overall idea looks great to me :-)

> Reviewed 4 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387#-:-NkcrbofEPaa8ENHCjwB:b-2xqbzh)* status: 4 of 48 files reviewed, 1 unresolved discussion (waiting on @blakehatch)

**Review by allada — COMMENTED** [review]
> Reviewed 79 of 79 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

___
*[`native-link-service/src/ac_server.rs` line 132 at r2](https://reviewable.io/reviews/tracemachina/native-link/387#-NksE7TI6XCUamM3_Y7s:-NksE7TI6XCUamM3_Y7t:b2bra4z) ([raw file](https://github.com/tracemachina/native-link/blob/e3b3c8ff69bb2f7025860af49b24aa644a65b5f2/native-link-service/src/ac_server.rs#L132)):*
> ```XML
> #[tonic::async_trait]
> impl ActionCache for AcServer {
>     #[instrument(skip(self), fields(response_time, hash, resp))]
> ```

nit: Should we maybe do this in a followup PR? Seems like we should do this in many places.
___
*[`src/bin/cas.rs` line 603 at r2](https://reviewable.io/reviews/tracemachina/native-link/387#-NksDZy67_iGZPQUNiEX:-NksDZy67_iGZPQUNiEY:b8u7u4w) ([raw file](https://github.com/tracemachina/native-link/blob/e3b3c8ff69bb2f7025860af49b24aa644a65b5f2/src/bin/cas.rs#L603)):*
> ```XML
> 
> fn main() -> Result<(), Box<dyn std::error::Error>> {
>     tracing_subscriber::fmt()
> ```

nit: Maybe it would be a good idea to do this in `ctor` like it was, but also give different defaults for `#[cfg(test)]`?

This would likely make debugging tests significantly easier/better.

**Review by allada — COMMENTED** [review]
Looking forward to this :-)

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387#-:-NksEFs1EJXbTy-DbsxQ:b-3v6w)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: 78 of 79 files reviewed, 1 unresolved discussion (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: 78 of 79 files reviewed, 1 unresolved discussion (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`native-link-service/src/ac_server.rs` line 132 at r2](https://reviewable.io/reviews/tracemachina/native-link/387#-NksE7TI6XCUamM3_Y7s:-NkvkrXcDiA7zfqdWaiO:b-vjuehq) ([raw file](https://github.com/tracemachina/native-link/blob/e3b3c8ff69bb2f7025860af49b24aa644a65b5f2/native-link-service/src/ac_server.rs#L132)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Should we maybe do this in a followup PR? Seems like we should do this in many places.
</blockquote></details>

Yeah this was intended as an example, but it seems better if the initial commit is as raw as possible.
___
*[`src/bin/cas.rs` line 603 at r2](https://reviewable.io/reviews/tracemachina/native-link/387#-NksDZy67_iGZPQUNiEX:-Nkvl0G817z5g73S0BUS:bab6rh) ([raw file](https://github.com/tracemachina/native-link/blob/e3b3c8ff69bb2f7025860af49b24aa644a65b5f2/src/bin/cas.rs#L603)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Maybe it would be a good idea to do this in `ctor` like it was, but also give different defaults for `#[cfg(test)]`?

This would likely make debugging tests significantly easier/better.
</blockquote></details>

I like the idea of getting better visibility into test runs, but am not convinced that `ctor` is the right approach. `tracing` depends on the stdlib and `ctor` explicitly warns against putting things that depend on std in the ctors.

Let's revisit this in another PR once we have proper subscriber logic set up.

**Review by aaronmondal — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387#-:-NkvmeHbBAVGzUS-Dqn7:bnfp4nl)* status: 78 of 79 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Review by allada — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/387)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adam-singer, @blakehatch, and @MarcusSorealheis)

**Pull request merged**
